In [1]:
import numpy as np

$G$: Graph as adjacency matrix

$X0$: Initial values as matrix, it has L column vectors, $X0_{i,j}=1$ iff the j-th sub-formula is of the type Color(x) and the i-th node in G satisfies it, in other case it's $0$

The formula for this example is $\varphi(x)=Red(x)\wedge\exists y(E(x,y)\wedge Blue(y))$

The graph chosen is $C_4$ where one node is Red and all others are Blue

In [2]:
L = 4
G = np.array([[0,1,1,0],[1,0,0,1],[1,0,0,1],[0,1,1,0]], np.int32)
X0 = np.array([[1,0,0,0],[0,1,0,0],[0,1,0,0],[0,1,0,0]])

In each step we take $X_i=ReLU(X_{i-1}\cdot A+G\cdot X_{i-1}\cdot C+b)$

In [3]:
A = np.array([[1,0,0,1],[0,1,0,0],[0,0,0,1],[0,0,0,0]])
C = np.array([[0,0,0,0],[0,0,1,0],[0,0,0,0],[0,0,0,0]])
b = np.array([[0,0,0,-1],[0,0,0,-1],[0,0,0,-1],[0,0,0,-1]])

In [4]:
print(G, X0, A, C, b, sep='\n')

[[0 1 1 0]
 [1 0 0 1]
 [1 0 0 1]
 [0 1 1 0]]
[[1 0 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]]
[[1 0 0 1]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 0 0]]
[[0 0 0 0]
 [0 0 1 0]
 [0 0 0 0]
 [0 0 0 0]]
[[ 0  0  0 -1]
 [ 0  0  0 -1]
 [ 0  0  0 -1]
 [ 0  0  0 -1]]


In [5]:
# Save each state in states
states = (L+1)*[None]
states[0] = X0

In [6]:
for i in range(L):
    X0 = np.add(np.add(np.matmul(X0, A),np.matmul(np.matmul(G, X0),C)),b)
    np.maximum(X0,0,X0)
    np.minimum(X0,1,X0)
    states[i+1] = X0

In [7]:
X0 # X0_iL=1 iff the i-th node of G satisfies the formula

array([[1, 0, 1, 1],
       [0, 1, 1, 0],
       [0, 1, 1, 0],
       [0, 1, 1, 0]])

In [8]:
print('\n'.join(map(str,states))) # States from X0 to XL

[[1 0 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]]
[[1 0 1 0]
 [0 1 1 0]
 [0 1 1 0]
 [0 1 1 0]]
[[1 0 1 1]
 [0 1 1 0]
 [0 1 1 0]
 [0 1 1 0]]
[[1 0 1 1]
 [0 1 1 0]
 [0 1 1 0]
 [0 1 1 0]]
[[1 0 1 1]
 [0 1 1 0]
 [0 1 1 0]
 [0 1 1 0]]
